services:
  postgres:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: movie_api_user
      POSTGRES_PASSWORD: movie_api_pass
      POSTGRES_DB: movie_api_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - movie_api_network

  fastapi:
    build: .
    container_name: fastapi_app
    command: python start.py
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      ENVIRONMENT: development
      DATABASE_URL: "postgresql+asyncpg://movie_api_user:movie_api_pass@postgres_db:5432/movie_api_db"
    networks:
      - movie_api_network

volumes:
  postgres_data:

networks:
  movie_api_network:
    driver: bridge
